//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopAplicationCV.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DesktopAplicationCV.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar.
        /// </summary>
        public static string Agregar {
            get {
                return ResourceManager.GetString("Agregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banco.
        /// </summary>
        public static string Banco {
            get {
                return ResourceManager.GetString("Banco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle Bancario.
        /// </summary>
        public static string BancoDetalle {
            get {
                return ResourceManager.GetString("BancoDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione el módulo con el que desea operar. .
        /// </summary>
        public static string Bienvenida {
            get {
                return ResourceManager.GetString("Bienvenida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar Sesion.
        /// </summary>
        public static string CerrarSesion {
            get {
                return ResourceManager.GetString("CerrarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuentas.
        /// </summary>
        public static string Cuentas {
            get {
                return ResourceManager.GetString("Cuentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Detalle.
        /// </summary>
        public static string Detalles {
            get {
                return ResourceManager.GetString("Detalles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string Editar {
            get {
                return ResourceManager.GetString("Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egresos.
        /// </summary>
        public static string Egreso {
            get {
                return ResourceManager.GetString("Egreso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        public static string Eliminar {
            get {
                return ResourceManager.GetString("Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha producido un error durante la autenticacion, verificar Web API..
        /// </summary>
        public static string ErrorAPI {
            get {
                return ResourceManager.GetString("ErrorAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha producido un error de tipo &quot;Catch&quot;, vuelva a intentarlo..
        /// </summary>
        public static string ErrorCatch {
            get {
                return ResourceManager.GetString("ErrorCatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifique las credenciales de acceso y vuelva a intentarlo..
        /// </summary>
        public static string ErrorCredenciales {
            get {
                return ResourceManager.GetString("ErrorCredenciales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha producido un error al momento de eliminar una fila..
        /// </summary>
        public static string ErrorEliminarFila {
            get {
                return ResourceManager.GetString("ErrorEliminarFila", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factura de Compras.
        /// </summary>
        public static string FacturaCompra {
            get {
                return ResourceManager.GetString("FacturaCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle de Factura de Compras.
        /// </summary>
        public static string FacturaCompraDetalle {
            get {
                return ResourceManager.GetString("FacturaCompraDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturas de Ventas.
        /// </summary>
        public static string FacturaVentas {
            get {
                return ResourceManager.GetString("FacturaVentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle de Factura de Ventas.
        /// </summary>
        public static string FacturaVentasDetalle {
            get {
                return ResourceManager.GetString("FacturaVentasDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar.
        /// </summary>
        public static string Ingresar {
            get {
                return ResourceManager.GetString("Ingresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresos.
        /// </summary>
        public static string Ingresos {
            get {
                return ResourceManager.GetString("Ingresos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle de Ingresos.
        /// </summary>
        public static string IngresosDetalle {
            get {
                return ResourceManager.GetString("IngresosDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metodo de Pago.
        /// </summary>
        public static string Metodo_Pago {
            get {
                return ResourceManager.GetString("Metodo_Pago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monedas.
        /// </summary>
        public static string Moneda {
            get {
                return ResourceManager.GetString("Moneda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CV Project.
        /// </summary>
        public static string NombreProyecto {
            get {
                return ResourceManager.GetString("NombreProyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Busqueda.
        /// </summary>
        public static string PlaceHoldBuscar {
            get {
                return ResourceManager.GetString("PlaceHoldBuscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productos.
        /// </summary>
        public static string Productos {
            get {
                return ResourceManager.GetString("Productos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verificar conexión..
        /// </summary>
        public static string SinConexion {
            get {
                return ResourceManager.GetString("SinConexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Socio de Negocio.
        /// </summary>
        public static string SocioNegocio {
            get {
                return ResourceManager.GetString("SocioNegocio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubTipo.
        /// </summary>
        public static string SubTipos {
            get {
                return ResourceManager.GetString("SubTipos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string Tipo {
            get {
                return ResourceManager.GetString("Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaccion Detalle.
        /// </summary>
        public static string TransaccionDetalle {
            get {
                return ResourceManager.GetString("TransaccionDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transacciones.
        /// </summary>
        public static string Transacciones {
            get {
                return ResourceManager.GetString("Transacciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario:.
        /// </summary>
        public static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volver.
        /// </summary>
        public static string Volver {
            get {
                return ResourceManager.GetString("Volver", resourceCulture);
            }
        }
    }
}
